# Generated by Django 2.1.7 on 2019-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
                ('test_id', models.CharField(max_length=2)),
                ('starred', models.BooleanField(default=False)),
            ],
        ),
    ]
